#
###################################
# Site wide configuration
####################################
#
title: Josef Adlao | Blog
email: josef@josefadlao.com
description: 
url: https://jadlao.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Australia/Sydney
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/posts/:year-:month/:title
sass: 
  sass_dir: _sass

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Josef Adlao
  avatar: 
  job: "Frontend Developer"
  bio: "A frontend developer from Sydney, Australia."
  email: josef@josefadlao.com
  disqus-shortname: jadlao
  twitter: josefadlao #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jadlao #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: josefadlao #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  twitter: josefadlao
